#!/bin/bash

while true; do

	dwmweather > /home/steve/dwmscripts/dwmweather.txt
	dwmupdates > /home/steve/dwmscripts/dwmupdates.txt

	sleep 3600s

done &

while true; do

	CPU=$(dwmcpu)
	MEM=$(dwmmemory)
	HDD=$(dwmdisk)
	UPDATES=$(< /home/steve/dwmscripts/dwmupdates.txt)
	TIME=$(dwmclock)
	xsetroot -name "|$CPU|$MEM|$HDD|$UPDATES|$TIME"

	sleep 5s
	
done &
